import { jsPDF } from "jspdf";
import type { Analysis } from "./store";

export function generateReportPdf(a: Analysis) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const w = doc.internal.pageSize.getWidth();
  let y = 48;

  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, w, 72, "F");
  doc.setTextColor(255);
  doc.setFontSize(20);
  doc.text("CrowdVision AI — Analysis Report", 40, 44);

  doc.setTextColor(30);
  y = 108;
  doc.setFontSize(11);
  doc.text(`File: ${a.fileName}`, 40, y);
  doc.text(`Generated: ${new Date(a.createdAt).toLocaleString()}`, 40, y + 16);
  doc.text(`Type: ${a.fileType.toUpperCase()}`, 40, y + 32);

  y += 68;
  doc.setFontSize(14);
  doc.text("Summary", 40, y);
  y += 8;
  doc.setDrawColor(220);
  doc.line(40, y, w - 40, y);
  y += 20;

  doc.setFontSize(11);
  const rows: [string, string][] = [
    ["People Count", String(a.peopleCount)],
    ["Density (per 100 sq units)", String(a.density)],
    ["Density Level", a.densityLabel],
    ["Risk Level", a.risk],
    ["Risk Score", `${a.riskScore}/100`],
    ["Predicted count (15 min)", String(a.prediction?.expectedCount ?? "—")],
    ["Predicted risk (15 min)", a.prediction?.expectedRisk ?? "—"],
  ];
  if (a.confidence != null) rows.push(["Model confidence", `${a.confidence}%`]);
  if (a.verified) rows.push(["AI verified count", String(a.aiCount ?? "—")]);
  rows.forEach(([k, v]) => {
    doc.setTextColor(90);
    doc.text(k, 40, y);
    doc.setTextColor(20);
    doc.text(v, 260, y);
    y += 18;
  });

  y += 12;
  doc.setFontSize(14);
  doc.text("Zone Density", 40, y);
  y += 8;
  doc.line(40, y, w - 40, y);
  y += 20;
  doc.setFontSize(11);
  const pageH = doc.internal.pageSize.getHeight();
  const brk = () => {
    if (y > pageH - 60) {
      doc.addPage();
      y = 60;
    }
  };
  (a.zones ?? []).forEach((z) => {
    brk();
    doc.setTextColor(90);
    doc.text(`Zone ${z.id}`, 40, y);
    doc.setTextColor(20);
    doc.text(`${z.count} people`, 160, y);
    doc.text(`Level: ${z.level}`, 280, y);
    y += 16;
  });

  // jsPDF core fonts cannot render emoji glyphs — strip them for the report.
  const plain = (s: string) =>
    s.replace(/[\u{1F000}-\u{1FAFF}\u{2600}-\u{27BF}\u{FE0F}\u{2194}-\u{21AA}]/gu, "").trim();

  if (a.cpri != null) {
    y += 12;
    brk();
    doc.setFontSize(14);
    doc.setTextColor(20);
    doc.text("Crowd Pressure & Risk Index (CPRI)", 40, y);
    y += 8;
    doc.line(40, y, w - 40, y);
    y += 20;
    doc.setFontSize(11);
    doc.text(`CPRI: ${a.cpri}/100  —  Band: ${a.cpriBand ?? "-"}`, 40, y);
    y += 16;
    if (a.cpriSub) {
      brk();
      doc.setTextColor(90);
      doc.text(
        `Sub-indices — density ${a.cpriSub.density}, turbulence ${a.cpriSub.turbulence}, egress ${a.cpriSub.egress}, occupancy ${a.cpriSub.occupancy}`,
        40,
        y,
      );
      doc.setTextColor(20);
      y += 18;
    }
    (a.alerts ?? []).forEach((al) => {
      brk();
      doc.text(`• ${plain(al)}`, 48, y);
      y += 14;
    });
  }

  y += 12;
  brk();
  doc.setFontSize(14);
  doc.text("Recommendations", 40, y);
  y += 8;
  doc.line(40, y, w - 40, y);
  y += 20;
  doc.setFontSize(11);
  doc.setTextColor(20);
  (a.recommendations ?? []).forEach((r, i) => {
    brk();
    const lines = doc.splitTextToSize(`${i + 1}. ${plain(r)}`, w - 80);
    doc.text(lines, 40, y);
    y += lines.length * 14 + 4;
  });


  doc.setFontSize(9);
  doc.setTextColor(140);
  doc.text(
    "Generated by CrowdVision AI — Intelligent Crowd Risk Prediction & Decision Support",
    40,
    doc.internal.pageSize.getHeight() - 24,
  );

  doc.save(`crowdvision-report-${a.id.slice(0, 8)}.pdf`);
}
